builds:
  - main: ./cli/terrapolicy
    binary: terrapolicy
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goarch: arm64
        goos: windows
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto
